import { describe, expect, test } from "bun:test";
import { presentPortalNotification, notificationAppearance } from "@/utils/portal-notification";
import { getCalendarReminderMinutes, getCalendarReminderTime, mergeCalendarReminders } from "@/utils/calendar-reminders";
import type { AcademicEvent, PortalNotification } from "@/types";
const notification = (kind: string, title: string, body: string): PortalNotification => ({id:"test",kind,title,body,link:null,createdAt:new Date().toISOString(),readAt:null});
const event: AcademicEvent = { id:"event",title:"Club event",date:"2026-10-05",category:"club",termId:"odd-2026-27",startAt:"2026-10-05T11:00:00Z",visibility:"public",origin:"google-calendar" };
describe("notification presentation and reminder semantics", () => {
 test("absence uses subject name with only the date below", () => expect(presentPortalNotification(notification("ATTENDANCE_ABSENT","Marked absent — CSS311","You were marked absent in Parallel and Distributed Computing on 2026-10-01."))).toEqual({title:"Marked absent: Parallel and Distributed Computing",body:"1 Oct"}));
 test("shortage extracts subject and current percentage without advice or code", () => expect(presentPortalNotification(notification("ATTENDANCE_SHORTAGE","Low attendance — IHS311 (57.14%)","Your attendance in Human Resource Management is 57.14%, below the required 65%. Please attend classes to stay exam-eligible."))).toEqual({title:"Low attendance: Human Resource Management",body:"57.14%"}));
 test("falls back to course lookup without displaying the code", () => expect(presentPortalNotification(notification("ATTENDANCE_ABSENT","Marked absent — CSE311",""),[{courseCode:"CSE311",courseName:"CSE311 - Artificial Intelligence"}]).title).toBe("Marked absent: Artificial Intelligence"));
 test("icons distinguish absence, pending leave, approved leave, shortage", () => expect(new Set(["ATTENDANCE_ABSENT","STUDENT_LEAVE_ADVISOR_APPROVED","STUDENT_LEAVE_APPROVED","ATTENDANCE_SHORTAGE"].map(k=>notificationAppearance(k).icon)).size).toBe(4));
 test("calendar honors explicit deadline and reminders, defaults to 30 minutes", () => {expect(getCalendarReminderTime({...event,deadlineAt:"2026-10-05T13:00:00Z"})).toBe(Date.parse("2026-10-05T13:00:00Z"));expect(getCalendarReminderMinutes(event)).toEqual([30]);expect(getCalendarReminderMinutes({...event,reminderMinutes:[10,60,10,-1,NaN]})).toEqual([60,10]);expect(getCalendarReminderMinutes({...event,reminderMinutes:[]})).toEqual([]);});
 test("hidden and private entries cannot schedule reminders; overrides replace time", () => {expect(mergeCalendarReminders([event,{...event,id:"private",visibility:"private"}],{event:{startAt:"2026-10-06T11:00:00Z"}})).toEqual([{...event,startAt:"2026-10-06T11:00:00Z"}]);expect(mergeCalendarReminders([event],{event:{hidden:true}})).toEqual([]);});
 test("date-only events use campus timezone and tentative/invalid dates stay silent", () => {expect(getCalendarReminderTime({...event,startAt:undefined})).toBe(Date.parse("2026-10-05T09:00:00+05:30"));expect(getCalendarReminderTime({...event,isTentative:true})).toBeNull();expect(getCalendarReminderTime({...event,startAt:"bad"})).toBeNull();});
});
