// Auto-generated by src/scripts/fetch-faculty.mjs
// Source: https://www.iiitkottayam.ac.in/#!/campus/hostel
import type { HostelGroup } from "@/types";

export const hostelGroups: HostelGroup[] = [
  {
    id: "anamudi",
    name: "Anamudi | Sahyadri",
    wardenIds: [
      "dr-kanchan-lata-kashyap",
      "dr-asha-sebastian",
      "dr-suriyapriya-k",
      "dr-dhakshayani-j",
      "dr-anu-maria-sebastian",
      "dr-gayathri-g-r",
      "dr-jeena-thomas",
    ],
  },
  {
    id: "meenachil",
    name: "Meenachil | Chittar",
    wardenIds: [
      "dr-ananth-a",
      "dr-vengadeswaran-s",
      "dr-s-jai-ganesh",
      "dr-mirothali-chand-c",
    ],
  },
  {
    id: "manimala",
    name: "Manimala | MJ Apartment",
    wardenIds: [
      "dr-sivaiah-bellamkonda",
      "dr-koppala-guravaiah",
      "dr-balasubramanian-p",
      "dr-sridhar-raj-s",
    ],
  },
  {
    id: "nila",
    name: "Nila | Agasthya",
    wardenIds: [
      "dr-santhos-kumar-a",
      "dr-venkatesh-s",
      "dr-a-balu",
      "dr-e-silambarasan",
    ],
  },
  {
    id: "kalapurakkal",
    name: "Kalapurakkal | Cooptyre Arcade | Kalapurakkal Apartment | Sunshine Apartment",
    wardenIds: [
      "dr-jayakrushna-sahoo",
      "dr-john-paul-martin",
      "dr-amit-kumar-roy",
      "dr-a-v-prajeesh",
    ],
  },
  {
    id: "anna-residency",
    name: "Anna Residency | Maryland Panackal Residency | KTM Building | Pala Court Complex",
    wardenIds: [
      "dr-susheel-kumar-joshi",
      "dr-murugan-d",
      "dr-goutam-mali",
      "dr-r-tharaniya-sairaj",
      "dr-anandhu-mohan",
    ],
  },
];
